Using GPU for training.
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/gym/logger.py:30: UserWarning: [33mWARN: You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.[0m
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
Epoch 0, Score 0.0000, Loss 17.9020, Time 1.5596
Epoch 1, Score 0.0000, Loss 8.9967, Time 1.6141
Epoch 2, Score 0.0000, Loss 8.9821, Time 1.7528
Epoch 3, Score 0.0000, Loss 9.4137, Time 1.8105
Epoch 4, Score 0.0000, Loss 9.2924, Time 2.0322
Epoch 5, Score 0.0000, Loss 9.1610, Time 2.1090
Epoch 6, Score 0.0000, Loss 9.9234, Time 2.1898
Epoch 7, Score 0.0000, Loss 9.3558, Time 2.3121
Epoch 8, Score 0.0000, Loss 9.6571, Time 2.4171
Epoch 9, Score 0.0000, Loss 9.6071, Time 2.4879
Epoch 10, Score 0.0000, Loss 9.1806, Time 2.6689
Epoch 11, Score 0.0000, Loss 9.6502, Time 2.7609
Epoch 12, Score 0.0000, Loss 9.4709, Time 2.8771
Epoch 13, Score 1.0000, Loss 9.5638, Time 2.9123
Epoch 14, Score 0.0000, Loss 9.4151, Time 3.0918
Epoch 15, Score 0.0000, Loss 9.8424, Time 3.2295
Epoch 16, Score 0.0000, Loss 9.5329, Time 3.4493
Epoch 17, Score 0.0000, Loss 8.9343, Time 3.4375
Epoch 18, Score 0.0000, Loss 9.3664, Time 3.4382
Epoch 19, Score 0.0000, Loss 9.0451, Time 3.6527
Epoch 20, Score 0.0000, Loss 9.4473, Time 3.7764
Epoch 21, Score 0.0000, Loss 9.1047, Time 3.8523
Epoch 22, Score 0.0000, Loss 8.9019, Time 3.9543
Epoch 23, Score 0.0000, Loss 9.4618, Time 4.1712
Epoch 24, Score 0.0000, Loss 9.2625, Time 4.3336
